const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const bcrypt = require('bcryptjs');
const { sequelize, User, Category, Product } = require('./models');

async function seed() {
  try {
    // Veritabanını sıfırla — tüm tablolar yeniden oluşturulur
    await sequelize.query('SET FOREIGN_KEY_CHECKS = 0;');
    await sequelize.sync({ force: true });
    await sequelize.query('SET FOREIGN_KEY_CHECKS = 1;');
    console.log('✅ Tablolar sıfırlandı ve yeniden oluşturuldu.');

    // ---- ADMIN KULLANICI ----
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await User.create({
      name: 'Admin Kullanıcı',
      email: 'admin@example.com',
      password: hashedPassword,
      role: 'admin',
    });
    console.log('✅ Admin kullanıcı oluşturuldu -> email: admin@example.com / şifre: admin123');

    // ---- 13 KATEGORİ ----
    const categoryNames = [
      'Telefon',       // 1
      'Laptop',        // 2
      'Monitör',       // 3
      'Akıllı Saat',   // 4
      'Mouse',         // 5
      'Klavye',        // 6
      'Oyun',          // 7
      'Kamera',        // 8
      'Drone',         // 9
      'Ses',           // 10
      'Depolama',      // 11
      'Kulaklık',      // 12
      'Televizyon',    // 13
    ];

    const cats = {};
    for (const name of categoryNames) {
      const cat = await Category.create({ name });
      cats[name] = cat.id;
    }
    console.log(`✅ ${categoryNames.length} kategori oluşturuldu.`);

    // ---- HER KATEGORİDE TAM 10 ADET (TOPLAM 130 ÜRÜN) ----
    const allProducts = [
      // ═══════════════════════════════════════════
      //  1. AKILLI SAAT (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Xiaomi Watch 2 Pro',
        brand: 'Xiaomi',
        description: 'WearOS işletim sistemi, Snapdragon W5+ Gen 1 çip, AMOLED ekran ve gelişmiş sağlık takibi.',
        price: 7499.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '1.43" AMOLED', İşlemci: 'Snapdragon W5+ Gen 1', Batarya: '495 mAh', GPS: 'Çift Bant', SuGeçirmezlik: '5 ATM' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Xiaomi Watch S3',
        brand: 'Xiaomi',
        description: 'Değiştirilebilir çerçeve tasarımı, HyperOS entegrasyonu ve 15 güne varan pil ömrü.',
        price: 4999.00,
        stock: 45,
        imageUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '1.43" AMOLED', Batarya: '15 Gün', Çerçeve: 'Değiştirilebilir Bezeller', GPS: '5 Uydu GNSS' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Huawei Watch GT 5 Pro',
        brand: 'Huawei',
        description: 'Titanyum kasa, safir cam, 14 güne varan pil ömrü ve EKG analizi.',
        price: 13999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '1.43" AMOLED', Kasa: 'Titanyum & Seramik', Batarya: '14 Gün', SuGeçirmezlik: 'IP69K / 5 ATM' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Huawei Watch Ultimate',
        brand: 'Huawei',
        description: 'Zirkonyum bazlı sıvı metal kasa, 100 metreye kadar dalış desteği ve keşif modu.',
        price: 29999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '1.5" LTPO AMOLED', Malzeme: 'Zirkonyum Sıvı Metal', Dalış: '100m ISO 22810', Batarya: '14 Gün' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Apple Watch Ultra 2',
        brand: 'Apple',
        description: '49mm titanyum kasa, S9 SiP çip, 3000 nit ultra parlak ekran ve Çift Dokunuş hareketi.',
        price: 43999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '49mm Retina OLED (3000 nit)', İşlemci: 'S9 SiP', Batarya: '36 Saat', SuGeçirmezlik: '100m WR100' },
        categoryId: 'Akıllı Saat',
        isFeatured: true,
      },
      {
        name: 'Apple Watch Series 10',
        brand: 'Apple',
        description: 'En ince Apple Watch tasarımı, 46mm OLED ekran, S10 SiP çip ve uyku apnesi algılama.',
        price: 18499.00,
        stock: 35,
        imageUrl: '/hero-banners/watch-series-10.png',
        specs: { Ekran: '46mm Geniş Açılı OLED', İşlemci: 'S10 SiP', İnceik: '9.7 mm', Şarj: '30 dk %80' },
        categoryId: 'Akıllı Saat',
        isFeatured: true,
      },
      {
        name: 'Apple Watch SE (2nd Gen)',
        brand: 'Apple',
        description: 'Retina ekran, S8 SiP işlemci, Trafik Kazası Algılama ve uygun fiyatlı şık Apple Watch.',
        price: 10499.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '44mm OLED Retina', İşlemci: 'S8 SiP', SuGeçirmezlik: '50m WR50', KalpSensörü: '2. Nesil Optik' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Samsung Galaxy Watch 7',
        brand: 'Samsung',
        description: '3nm Exynos W1000 işlemci, BioActive sensör, Uyku Apnesi algılama ve Çift Frekanslı GPS.',
        price: 8999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '1.5" Super AMOLED', İşlemci: 'Exynos W1000 (3nm)', RAM: '2 GB', Depolama: '32 GB' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Amazfit Balance',
        brand: 'Amazfit',
        description: 'Vücut bileşimi analizi, AI koçluk desteği, 14 gün pil ömrü ve HD AMOLED ekran.',
        price: 6499.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '1.5" HD AMOLED', Batarya: '14 Gün', Sensör: 'BioTracker 5.0', GPS: '6 Uydu Sistemi' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },
      {
        name: 'Google Pixel Watch 3',
        brand: 'Google',
        description: 'Actua OLED ekran, Gemini AI entegrasyonu, gelişmiş Fitbit koşu analizi.',
        price: 14999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '45mm Actua OLED', İşlemci: 'SW5100', RAM: '2 GB', İşletimSistemi: 'Wear OS 5.0' },
        categoryId: 'Akıllı Saat',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  2. DEPOLAMA (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Samsung 990 PRO NVMe SSD 2TB',
        brand: 'Samsung',
        description: '7450 MB/s okuma, 6900 MB/s yazma hızı, PCIe 4.0 NVMe M.2 yüksek performans SSD.',
        price: 6899.00,
        stock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '2 TB', OkumaHızı: '7450 MB/s', YazmaHızı: '6900 MB/s', Arabirim: 'PCIe Gen 4.0 x4 M.2' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'Samsung T7 Portable SSD 1TB',
        brand: 'Samsung',
        description: '1050 MB/s okuma hızı, darbeye dayanıklı alüminyum gövde ve USB 3.2 Gen 2 bağlantı.',
        price: 3499.00,
        stock: 45,
        imageUrl: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '1 TB', OkumaHızı: '1050 MB/s', Arabirim: 'USB 3.2 Gen 2 Type-C', Şifreleme: 'AES 256-bit' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'Samsung 870 EVO SATA III SSD 1TB',
        brand: 'Samsung',
        description: '560 MB/s okuma, 530 MB/s yazma hızı ile masaüstü ve laptoplar için güvenilir depolama.',
        price: 2699.00,
        stock: 60,
        imageUrl: 'https://images.unsplash.com/photo-1628557044797-f21a177c37ec?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '1 TB', FormFaktörü: '2.5 inç SATA III', OkumaHızı: '560 MB/s', YazmaHızı: '530 MB/s' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'Kingston Fury Renegade NVMe SSD 1TB',
        brand: 'Kingston',
        description: '7300 MB/s okuma hızı, Graphene alüminyum soğutucu etiketi ile oyun odaklı depolama.',
        price: 3899.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '1 TB', OkumaHızı: '7300 MB/s', YazmaHızı: '6000 MB/s', Arabirim: 'PCIe 4.0 NVMe' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'Kingston DataTraveler Max 512GB Flash Drive',
        brand: 'Kingston',
        description: 'USB 3.2 Gen 2 Type-C flash bellek, 1000 MB/s yüksek hızlı veri aktarımı.',
        price: 1899.00,
        stock: 55,
        imageUrl: 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '512 GB', OkumaHızı: '1000 MB/s', Arabirim: 'USB 3.2 Gen 2 Type-C', Tasarım: 'Kaydırmalı Kapak' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'SanDisk Extreme Portable SSD 2TB',
        brand: 'SanDisk',
        description: 'IP65 suya ve toza dayanıklı outdoor taşınabilir SSD, 1050 MB/s aktarım.',
        price: 5999.00,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '2 TB', Koruma: 'IP65 Su/Toz', OkumaHızı: '1050 MB/s', DüşmeDayanımı: '3 Metre' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'SanDisk Ultra Dual Drive Luxe 256GB',
        brand: 'SanDisk',
        description: 'Tüm metal gövdeli hem Type-C hem Type-A çift konnektörlü akıllı telefon ve PC flash sürücü.',
        price: 899.00,
        stock: 70,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
        specs: { Kapasite: '256 GB', Arabirim: 'USB Type-C + Type-A', OkumaHızı: '150 MB/s', Malzeme: 'Döküm Metal' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'Asustor AS6704T 4-Bay NAS',
        brand: 'Asustor',
        description: 'Intel Celeron N5105 quad-core işlemci, 4x M.2 NVMe yuvası, 2.5GbE çift port sunucu.',
        price: 21999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Intel Celeron N5105', RAM: '4 GB DDR4', Portlar: 'Çift 2.5GbE', Yuva: '4x SATA + 4x M.2 NVMe' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'Asustor Drivestor 2 Pro AS1102T',
        brand: 'Asustor',
        description: 'Realtek Quad-Core işlemci, 2.5GbE bağlantı portu ile bütçe dostu 2 yuvalı ev NAS sistemi.',
        price: 8499.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1537498425277-c283d32ef9db?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Realtek RTD1296 Quad-Core', RAM: '1 GB Realtek', Port: '1x 2.5GbE', Yuva: '2x 3.5" SATA' },
        categoryId: 'Depolama',
        isFeatured: false,
      },
      {
        name: 'MSI PRO Z890-A WIFI',
        brand: 'MSI',
        description: 'Yeni nesil Intel LGA 1851 soket, DDR5 bellek desteği, PCIe 5.0 ve Wi-Fi 7 anakart.',
        price: 14499.00,
        stock: 22,
        imageUrl: '/hero-banners/pro-z890-a-wifi.png',
        specs: { Soket: 'LGA 1851', RAM: 'DDR5 8800+ MHz', DepolamaYuvaları: '4x M.2 PCIe 5.0/4.0', Kablosuz: 'Wi-Fi 7 + Bluetooth 5.4' },
        categoryId: 'Depolama',
        isFeatured: true,
      },

      // ═══════════════════════════════════════════
      //  3. DRONE (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'DJI Mini 4 Pro',
        brand: 'DJI',
        description: '249 gram altı ultra hafif, 4K/60fps HDR video, Her Yöne Engel Algılama ve 34 dk uçuş.',
        price: 32999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&auto=format&fit=crop&q=80',
        specs: { Ağırlık: '249g', Kamera: '4K/60fps HDR', UçuşSüresi: '34 Dakika', Menzil: '20 km O4' },
        categoryId: 'Drone',
        isFeatured: true,
      },
      {
        name: 'DJI Avata 2',
        brand: 'DJI',
        description: 'FPV serbest uçuş deneyimi, 4K Ultra Geniş Açılı kamera, 23 dakika uçuş ve Entegre Pervane Koruması.',
        price: 39999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&auto=format&fit=crop&q=80',
        specs: { GörüşAçısı: '155° Ultra Geniş', UçuşSüresi: '23 Dakika', Sensör: '1/1.3 inç CMOS', Gözlük: 'DJI Goggles 3' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'DJI Air 3 Fly More Combo',
        brand: 'DJI',
        description: 'Çift ana kamera (Geniş + 3x Telefoto), 48MP fotoğraflar, 46 dakika uçuş süresi.',
        price: 54999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&auto=format&fit=crop&q=80',
        specs: { Kameralar: 'Çift 1/1.3" CMOS', UçuşSüresi: '46 Dakika', Video: '4K/100fps', EngelAlgılama: 'Her Yöne' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'DJI Mavic 3 Pro',
        brand: 'DJI',
        description: 'Üçlü Hasselblad kamera sistemi, 5.1K Apple ProRes video desteği ve 43 dakika uçuş.',
        price: 89999.00,
        stock: 8,
        imageUrl: 'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '4/3 CMOS Hasselblad', Telefoto: '70mm & 166mm Çift Tele', UçuşSüresi: '43 Mins', ProRes: 'Apple ProRes 422 HQ' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'Corby CX007 Smart Drone',
        brand: 'Corby',
        description: 'Wi-Fi kameralı, otomatik pilot katlanabilir başlangıç seviyesi drone.',
        price: 2499.00,
        stock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=600&auto=format&fit=crop&q=80',
        specs: { Kamera: '720p HD', UçuşSüresi: '10 Dakika', Kumanda: 'Telefon & Wi-Fi', Özellik: 'Otomatik Havada Kalma' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'Corby CX014 Zoom Drone',
        brand: 'Corby',
        description: '1080p Full HD ayarlanabilir kameralı, 360 derece takla atma özellikli drone.',
        price: 3499.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=600&auto=format&fit=crop&q=80',
        specs: { Kamera: '1080p Full HD', UçuşSüresi: '14 Dakika', Hareket: '360° Akrobatik Takla', Kumanda: '2.4GHz Kumanda' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'Insta360 Sphere 360 Drone Kamerası',
        brand: 'Insta360',
        description: 'Mavic Air 2/2S drone modelleri için görünmez 5.7K 360 derece çekim eklentisi.',
        price: 19999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?w=600&auto=format&fit=crop&q=80',
        specs: { Çözünürlük: '5.7K 360° Video', Uyumluluk: 'DJI Mavic Air 2 / 2S', Stabilizasyon: 'FlowState' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'Insta360 Antigravity Drone Cam Kit',
        brand: 'Insta360',
        description: 'Hava çekimlerinde dronun gövdesini silen özel 360° panorama kamera kiti.',
        price: 24999.00,
        stock: 14,
        imageUrl: 'https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?w=600&auto=format&fit=crop&q=80',
        specs: { Çekim: 'Invisible Drone Lens', Çözünürlük: '8K 30fps', Stabilizasyon: '6-Axis Gyro' },
        categoryId: 'Drone',
        isFeatured: false,
      },
      {
        name: 'Autel Robotics EVO Max 4N',
        brand: 'Autel Robotics',
        description: 'Gece görüş kamerası, 48MP termal/optik sensör, 42 dakika uçuş süresi profesyonel drone.',
        price: 189999.00,
        stock: 5,
        imageUrl: '/hero-banners/robotics-evo-max-4n.png',
        specs: { Kamera: 'Night Vision Starlight + Thermal', UçuşSüresi: '42 Dakika', Menzil: '20 km SkyLink 3.0', Koruma: 'IP43' },
        categoryId: 'Drone',
        isFeatured: true,
      },
      {
        name: 'Autel Robotics EVO Lite+ Premium Bundle',
        brand: 'Autel Robotics',
        description: '1 inç CMOS sensör, f/2.8-f/11 ayarlanabilir diyafram, 6K/30fps HDR video kaydı.',
        price: 48999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1506947411487-a56738267384?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '1" CMOS 20MP', Video: '6K 30fps', UçuşSüresi: '40 Mins', Diyafram: 'f/2.8 - f/11' },
        categoryId: 'Drone',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  4. KAMERA (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Canon EOS R6 Mark II',
        brand: 'Canon',
        description: '24.2 MP Tam Kare CMOS sensör, 40 fps sürekli çekim ve 4K 60p aşırı örneklenmiş video kaydı.',
        price: 89999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '24.2 MP Full-Frame', Odaklama: 'Dual Pixel CMOS AF II', SeriÇekim: '40 fps', Video: '4K 60p Uncropped' },
        categoryId: 'Kamera',
        isFeatured: true,
      },
      {
        name: 'Canon EOS R50',
        brand: 'Canon',
        description: '24.2 MP APS-C sensör, 4K 30p video kaydı, hafif tasarım ile başlangıç ve vlogging kamerası.',
        price: 26999.00,
        stock: 22,
        imageUrl: 'https://images.unsplash.com/photo-1519638399535-1b036603ac77?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '24.2 MP APS-C', Odaklama: 'Dual Pixel CMOS AF II', Ağırlık: '375g', Ekran: 'Dönebilir Dokunmatik' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'Sony Alpha A7 IV',
        brand: 'Sony',
        description: '33 MP BSI CMOS sensör, BIONZ XR işlemci, 4K 60p 10-bit video ve yapay zeka odaklama.',
        price: 84999.00,
        stock: 16,
        imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '33 MP Full-Frame BSI', ISO: '100 - 51200', Vizör: '3.68M nokta OLED', Stabilizasyon: '5-Eksenli IBIS' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'Sony ZV-E10',
        brand: 'Sony',
        description: '24.2 MP APS-C Değiştirilebilir lensli vlogging kamerası, 4K video ve ürün sergileme modu.',
        price: 24999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '24.2 MP APS-C', Ekran: 'Dönebilir Dokunmatik LCD', Mikrofon: '3-Kapsüllü Yönlü', Video: '4K 30p' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'Insta360 Ace Pro 2',
        brand: 'Insta360',
        description: 'Leica lensli 8K aksiyon kamerası, çift AI işlemci ve 2.5 inç katlanabilir dokunmatik ekran.',
        price: 21999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=600&auto=format&fit=crop&q=80',
        specs: { Lens: 'Leica Summarit', Video: '8K 30fps / 4K 120fps', Ekran: '2.5" Katlanır Dokunmatik', SuGeçirmezlik: '12 Metre' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'Insta360 X4 Aksiyon Kamerası',
        brand: 'Insta360',
        description: '8K 360° video kaydı, FlowState stabilizasyon ve Görünmez Özçekim Çubuğu efekti.',
        price: 24999.00,
        stock: 28,
        imageUrl: '/hero-banners/x4-air-bundle.png',
        specs: { Video: '8K 30fps 360°', Fotoğraf: '72 MP 360°', Ekran: '2.5" Dayanıklı Cam Dokunmatik', SuGeçirmezlik: '10 Metre' },
        categoryId: 'Kamera',
        isFeatured: true,
      },
      {
        name: 'Nikon Z6 III',
        brand: 'Nikon',
        description: 'Dünyanın ilk Kısmen Yığınlanmış Full-Frame sensörlü kamerası, 6K RAW video kaydı.',
        price: 94999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '24.5 MP Partially-Stacked', Video: '6K 60p N-RAW', Vizör: '5.76M nokta 4000 nit', SeriÇekim: '120 fps' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'Nikon Z50',
        brand: 'Nikon',
        description: '20.9 MP APS-C aynasız kamera, compact hafif gövde ve 11 fps sürekli çekim hızı.',
        price: 31999.00,
        stock: 22,
        imageUrl: 'https://images.unsplash.com/photo-1500634245200-e5245c7e73ef?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '20.9 MP DX APS-C', Ekran: '180° Aşağı Katlanır LCD', Video: '4K UHD 30p', Ağırlık: '395g' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'GoPro HERO13 Black',
        brand: 'GoPro',
        description: '5.3K60 video, HB-Serisi lens serisi uyumluluğu, Enduro batarya ve Gelişmiş HyperSmooth 6.0.',
        price: 18999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1508898578281-774ac4893c0c?w=600&auto=format&fit=crop&q=80',
        specs: { Video: '5.3K 60fps / 4K 120fps', Fotoğraf: '27 MP', Stabilizasyon: 'HyperSmooth 6.0', SuGeçirmezlik: '10 Metre' },
        categoryId: 'Kamera',
        isFeatured: false,
      },
      {
        name: 'Fujifilm X-T5',
        brand: 'Fujifilm',
        description: '40.2 MP X-Trans CMOS 5 HR sensör, klasik kadranlı tasarım ve 7 duraklı 5 eksenli IBIS.',
        price: 64999.00,
        stock: 14,
        imageUrl: 'https://images.unsplash.com/photo-1512790182412-b19e6d61b397?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: '40.2 MP X-Trans CMOS 5', İşlemci: 'X-Processor 5', FilmSimülasyonu: '19 Mod', Video: '6.2K 30p 10-bit' },
        categoryId: 'Kamera',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  5. KLAVYE (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Razer Huntsman V3 Pro',
        brand: 'Razer',
        description: 'Gen-2 Analog Optik Anahtarlar, Rapid Trigger modu ve ayarlanabilir aktivasyon mesafesi.',
        price: 9999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'Razer Analog Optical Gen-2', RapidTrigger: '0.1 - 4.0 mm', Tuşlar: 'PBT Double-shot', Ekran: 'OLED Komuta Alanı' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'Razer BlackWidow V4 Pro',
        brand: 'Razer',
        description: 'Mekanik Green/Yellow switch, Komuta Çarkı, 8 Makro Tuşu ve 3 taraflı alt RGB aydınlatma.',
        price: 8999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'Razer Mechanical Yellow', PollingRate: '8000Hz', Makro: '8 Özel Tuş', RGB: 'Razer Chroma Per-Key' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'Logitech G PRO X TKL',
        brand: 'Logitech',
        description: 'LIGHTSPEED kablosuz mekanik oyuncu klavyesi, GX Switch seçenekleri ve RGB LIGHTSYNC.',
        price: 7999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'GX Brown Tactile / Red Linear', Kablosuz: 'LIGHTSPEED + Bluetooth', Pil: '50 Saat', Tuşlar: 'PBT Keycaps' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'Logitech MX Keys S',
        brand: 'Logitech',
        description: 'Gelişmiş kablosuz klavye, Perfect Stroke tuşlar, akıllı aydınlatma ve çoklu cihaz geçişi.',
        price: 4699.00,
        stock: 45,
        imageUrl: 'https://images.unsplash.com/photo-1541140134513-85a161dc4a00?w=600&auto=format&fit=crop&q=80',
        specs: { TuşTipi: 'Spherical-Dished Keys', Bağlantı: 'Logi Bolt + Bluetooth', ÇokluCihaz: '3 Cihaz Easy-Switch', Pil: '10 Gün' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'Corsair K100 RGB',
        brand: 'Corsair',
        description: 'OPX Optik-Mekanik anahtarlar, AXON 4000Hz hyper-polling teknolojisi ve iCUE kontrol çarkı.',
        price: 8999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'CORSAIR OPX Optical', PollingRate: '4000Hz', Kasa: 'Anodize Alüminyum', BilekDesteği: 'Deri Hafızalı Köpük' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'Corsair K70 MAX RGB',
        brand: 'Corsair',
        description: 'MGX Ayarlanabilir manyetik-optik anahtarlar, çift aşamalı aktivasyon ve PBT tuş kapakları.',
        price: 7899.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'CORSAIR MGX Magnetic', RapidTrigger: '0.4 - 3.6mm', Gövde: 'Alüminyum Kasa', Sesİzolasyonu: 'Çift Katman Köpük' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'SteelSeries Apex Pro TKL',
        brand: 'SteelSeries',
        description: 'OmniPoint 2.0 ayarlanabilir manyetik anahtarlar, OLED akıllı ekran ve alüminyum kasa.',
        price: 8499.00,
        stock: 22,
        imageUrl: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'OmniPoint 2.0 Magnetic', TepkiSüresi: '0.7ms', Ekran: 'OLED Smart Display', Düzen: 'TKL (%80)' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'Mercury V60 Pro HE',
        brand: 'Mercury',
        description: 'Şeffaf siber tasarım, manyetik Hall Effect tuşlar, 0.1mm hassasiyetli ayarlanabilir anahtarlar.',
        price: 6999.00,
        stock: 40,
        imageUrl: '/hero-banners/mercury-v60-pro.png',
        specs: { Switch: 'Magnetic Hall Effect', RapidTrigger: '0.1mm Hassasiyet', Tasarım: 'Şeffaf Kasalı %60', RGB: 'Gelişmiş RGB Matrix' },
        categoryId: 'Klavye',
        isFeatured: true,
      },
      {
        name: 'GravaStar K1 Pro Mekanik Klavye',
        brand: 'GravaStar',
        description: 'Bilim kurgu alüminyum alaşım iskelet tasarım, hotswap mekanik tuşlar ve custom ses izolasyonu.',
        price: 7499.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1563198804-b19d095b3042?w=600&auto=format&fit=crop&q=80',
        specs: { Switch: 'Kailh Linear Custom', Gövde: 'Çinko Alaşım', Bağlantı: 'Üçlü Mod (2.4G/BT/Kablo)', Yapı: 'Gasket Mount' },
        categoryId: 'Klavye',
        isFeatured: false,
      },
      {
        name: 'GravaStar Mercury K1 Wireless Gaming Keyboard',
        brand: 'GravaStar',
        description: 'Retro-futuristic tasarım, contalı montaj yapısı, PBT tuş takımları ve RGB aydınlatma.',
        price: 7999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1567928269937-ae146e45b428?w=600&auto=format&fit=crop&q=80',
        specs: { Yapı: 'Gasket Mount 75%', Bağlantı: '2.4GHz + BT + Type-C', Switch: 'GravaStar x Kailh Linear', Pil: '4000 mAh' },
        categoryId: 'Klavye',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  6. KULAKLIK (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'JBL Tour One M2',
        brand: 'JBL',
        description: 'True Adaptive ANC gürültü engelleme, Hi-Res Personi-Fi 2.0 ses ve 50 saat pil ömrü.',
        price: 9999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
        specs: { Sürücü: '40mm Hi-Res', GürültüEngelleme: 'True Adaptive ANC', Pil: '50 Saat (ANC Kapalı)', Mikrofon: '4-Mic kristal görüşme' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'JBL Tune 770NC',
        brand: 'JBL',
        description: 'JBL Pure Bass ses kalitesi, Adaptif Gürültü Engelleme ve 70 saate kadar pil süresi.',
        price: 3499.00,
        stock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
        specs: { Sürücü: '40mm JBL Pure Bass', Pil: '70 Saat', Bağlantı: 'Bluetooth 5.3', Şarj: '5 dk şarj 3 saat' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'Sony WF-1000XM5 TWS',
        brand: 'Sony',
        description: 'Sektörün en iyi gürültü engelleyici TWS kulaklığı, Dynamic Driver X ve LDAC desteği.',
        price: 9499.00,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
        specs: { Sürücü: '8.4mm Dynamic Driver X', Kodek: 'LDAC / LC3 / AAC', Pil: '8+16 Saat', İşlemci: 'HD QN2e + V2' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'Sony WH-1000XM5',
        brand: 'Sony',
        description: 'Sektör lideri gürültü engelleme, 30 saat pil ömrü, 8 mikrofonlu Kristal Netliğinde görüşme.',
        price: 13999.00,
        stock: 45,
        imageUrl: '/hero-banners/wh-1000xm5.png',
        specs: { Sürücü: '30mm Karbon Elyaf', İşlemci: 'Integrated V1 + QN1', Pil: '30 Saat (ANC Açık)', Ağırlık: '250g' },
        categoryId: 'Kulaklık',
        isFeatured: true,
      },
      {
        name: 'AirPods Max 2',
        brand: 'Apple',
        description: 'USB-C şarj bağlantısı, H1 çipleri, Aktif Gürültü Engelleme ve Şeffaf Modlu premium ses.',
        price: 24999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
        specs: { Bağlantı: 'USB-C', İşlemci: 'Dual Apple H1', Ses: 'Kişiselleştirilmiş Uzamsal Ses', Pil: '20 Saat' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'AirPods Pro 2. Nesil (USB-C)',
        brand: 'Apple',
        description: 'H2 çip, 2 kata kadar daha fazla Aktif Gürültü Engelleme, Adaptif Ses ve USB-C şarj kutusu.',
        price: 9299.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Apple H2', ŞarjKutusu: 'MagSafe USB-C (Hoparlörlü)', Pil: '6+24 Saat', SuKoruma: 'IP54' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'Samsung Galaxy Buds3 Pro',
        brand: 'Samsung',
        description: 'Bıçak tasarımlı LED ışıklar, Çift Amfiler ile 24-bit Hi-Fi ses ve Galaxy AI çeviri desteği.',
        price: 6999.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&auto=format&fit=crop&q=80',
        specs: { Sürücü: '2-Yönlü Hoparlör (Planar+Woofer)', Ses: '24bit 96kHz SSC', GürültüEngelleme: 'Adaptive ANC', AI: 'Live Translate' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'Samsung Galaxy Buds FE',
        brand: 'Samsung',
        description: 'Ergonomik kanat ucu tasarımı, Güçlü ANC gürültü engelleme ve derin bas ses performansı.',
        price: 2499.00,
        stock: 60,
        imageUrl: 'https://images.unsplash.com/photo-1578319439584-104c94d37305?w=600&auto=format&fit=crop&q=80',
        specs: { Sürücü: '1-Yönlü 6.5mm', GürültüEngelleme: 'Aktif Gürültü Engelleme', Pil: '6+21 Saat', Dokunmatik: 'Kişiselleştirilebilir' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'Bose QuietComfort Ultra',
        brand: 'Bose',
        description: 'Bose Immersive Audio uzamsal ses, dünyaca ünlü sessizlik teknolojisi ve CustomTune kalibrasyonu.',
        price: 15999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&auto=format&fit=crop&q=80',
        specs: { Modlar: 'Quiet, Aware, Immersive', Pil: '24 Saat', Kalibrasyon: 'CustomTune', Bağlantı: 'Bluetooth 5.3 Multipoint' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },
      {
        name: 'Bose SoundSport Free',
        brand: 'Bose',
        description: 'Tere ve hava koşullarına dayanıklı, StayHear+ Sport kulak uçlu kablosuz spor kulaklığı.',
        price: 4999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&auto=format&fit=crop&q=80',
        specs: { Koruma: 'IPX4 Tere Dayanıklı', Pil: '5+10 Saat', KulakUçları: 'StayHear+ Sport 3 Boyut', Bluetooth: '10m Menzil' },
        categoryId: 'Kulaklık',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  7. LAPTOP (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Apple MacBook Pro 16 M3 Max',
        brand: 'Apple',
        description: '16 çekirdekli CPU, 40 çekirdekli GPU, 48GB Unifed RAM ve Liquid Retina XDR ekran.',
        price: 134999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Apple M3 Max (16-core)', RAM: '48 GB Unified', Depolama: '1 TB SSD', Ekran: '16.2" Liquid Retina XDR' },
        categoryId: 'Laptop',
        isFeatured: true,
      },
      {
        name: 'Apple MacBook Air 15 M3',
        brand: 'Apple',
        description: 'İnce 11.5mm alüminyum tasarım, M3 çip, 18 saate varan pil ömrü ve 15.3 inç Liquid Retina.',
        price: 54999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Apple M3 (8-core CPU / 10-core GPU)', RAM: '16 GB Unified', Depolama: '512 GB SSD', Ekran: '15.3" Liquid Retina' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'MSI Raider GE78 HX',
        brand: 'MSI',
        description: 'Intel Core i9-14900HX, RTX 4090 16GB ekran kartı, 240Hz QHD+ ekran ve Matrix RGB bar.',
        price: 149999.00,
        stock: 8,
        imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'i9-14900HX', GPU: 'RTX 4090 16GB (175W)', RAM: '64 GB DDR5', Ekran: '17" QHD+ 240Hz' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'Acer Predator Helios 16',
        brand: 'Acer',
        description: 'Intel i7-14700HX, RTX 4070 ekran kartı, Mini LED 250Hz WQXGA oyuncu bilgisayarı.',
        price: 69999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'i7-14700HX', GPU: 'RTX 4070 8GB', RAM: '32 GB DDR5', Ekran: '16" WQXGA Mini LED 250Hz' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'Acer Nitro V15',
        brand: 'Acer',
        description: 'RTX 4060 ekran kartı, Intel i7 işlemci ve 144Hz IPS ekran ile yüksek performanslı oyun laptopu.',
        price: 34999.00,
        stock: 30,
        imageUrl: '/hero-banners/nitro-v15.png',
        specs: { İşlemci: 'Intel Core i7-13620H', GPU: 'NVIDIA RTX 4060 8GB', RAM: '16 GB DDR5', Ekran: '15.6" FHD 144Hz IPS' },
        categoryId: 'Laptop',
        isFeatured: true,
      },
      {
        name: 'Lenovo Legion Pro 7i',
        brand: 'Lenovo',
        description: 'Intel i9-14900HX, RTX 4080 GPU, LA2-Q AI çipi ile optimize edilmiş 240Hz ekran.',
        price: 109999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'i9-14900HX', GPU: 'RTX 4080 12GB', RAM: '32 GB DDR5', Ekran: '16" 1600p 240Hz VRR' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'Huawei MateBook X Pro',
        brand: 'Huawei',
        description: '980 gram ultra hafif magnezyum gövde, Intel Core Ultra 9, 3.1K OLED esnek dokunmatik ekran.',
        price: 79999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Intel Core Ultra 9 185H', Ağırlık: '980 gram', Ekran: '14.2" 3.1K OLED 120Hz', RAM: '32 GB' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'HP OMEN 16',
        brand: 'HP',
        description: 'Ryzen 7 7840HS, RTX 4060, Tempest Cooling soğutma teknolojisi ve 165Hz IPS ekran.',
        price: 44999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Ryzen 7 7840HS', GPU: 'RTX 4060 8GB', RAM: '16 GB DDR5', Ekran: '16.1" FHD 165Hz' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'Dell XPS 16',
        brand: 'Dell',
        description: 'Intel Core Ultra 7, RTX 4060, 4K+ OLED dokunmatik ekran ve premium cam avuç içi dayanağı.',
        price: 99999.00,
        stock: 14,
        imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Core Ultra 7 155H', GPU: 'RTX 4060 8GB', Ekran: '16.3" 4K+ Touch OLED', RAM: '32 GB LPDDR5x' },
        categoryId: 'Laptop',
        isFeatured: false,
      },
      {
        name: 'ASUS ROG Strix SCAR 18',
        brand: 'Asus',
        description: 'Intel i9-14900HX, RTX 4090, ROG Nebula HDR Mini LED 240Hz ekran.',
        price: 154999.00,
        stock: 6,
        imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'i9-14900HX', GPU: 'RTX 4090 16GB', Ekran: '18" Mini LED 240Hz', RAM: '64 GB DDR5' },
        categoryId: 'Laptop',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  8. MONİTÖR (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Samsung Odyssey OLED G9 49"',
        brand: 'Samsung',
        description: '49 inç Dual QHD (5120x1440) kavisli OLED ekran, 240Hz tazeleme ve 0.03ms tepki süresi.',
        price: 49999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '49" Curved OLED (1800R)', Çözünürlük: '5120 x 1440', Yenileme: '240Hz', TepkiSüresi: '0.03ms GTG' },
        categoryId: 'Monitör',
        isFeatured: true,
      },
      {
        name: 'Samsung Odyssey Neo G8 32" 240Hz',
        brand: 'Samsung',
        description: 'Dünyanın ilk 4K 240Hz Mini-LED kavisli 1000R oyuncu monitörü, Quantum HDR 2000.',
        price: 36999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '32" 4K Mini-LED 1000R', Yenileme: '240Hz', TepkiSüresi: '1ms GTG', Parlaklık: '2000 nits' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'Samsung ViewFinity S9 5K 27"',
        brand: 'Samsung',
        description: '5K (5120x2880) çözünürlük, %99 DCI-P3 renk gamı, Thunderbolt 4 ve 4K SlimFit kamera.',
        price: 44999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '27" 5K IPS Matte Display', Çözünürlük: '5120 x 2880', Renk: '%99 DCI-P3', Portlar: 'Thunderbolt 4 (90W)' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'LG UltraGear 34GS95QE OLED 34"',
        brand: 'LG',
        description: '34 inç WQHD kavisli 240Hz OLED oyuncu monitörü, 800R kavis oranı ve VESA DisplayHDR True Black 400.',
        price: 39999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1551645120-d70bfe84c826?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '34" Curved OLED (800R)', Çözünürlük: '3440 x 1440', Yenileme: '240Hz', TepkiSüresi: '0.03ms' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'LG UltraGear 27GR95QE-B OLED 27"',
        brand: 'LG',
        description: '27 inç QHD (2560x1440) 240Hz OLED ekran, 0.03ms tepki süresi ve HDMI 2.1 desteği.',
        price: 29999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '27" QHD OLED Düz', Yenileme: '240Hz', TepkiSüresi: '0.03ms GTG', GSync: 'NVIDIA G-SYNC Compatible' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'LG MyView Smart Monitor 32"',
        brand: 'LG',
        description: '4K UHD IPS ekran, webOS 23 akıllı TV arayüzü, AirPlay 2 ve HomeKit desteği.',
        price: 13999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '31.5" 4K UHD IPS', İşletimSistemi: 'webOS 23 Smart', Bağlantı: 'USB-C (65W), HDMI x2, Wi-Fi' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'MSI MAG 321UPX QD-OLED 32"',
        brand: 'MSI',
        description: '32 inç 4K UHD QD-OLED ekran, 240Hz yenileme hızı ve Quantum Dot teknolojisi.',
        price: 42999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '31.5" 4K QD-OLED', Çözünürlük: '3840 x 2160', Yenileme: '240Hz', Garanti: '3 Yıl OLED Burn-in' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'MSI G274QPF-QD 27" 170Hz',
        brand: 'MSI',
        description: '27 inç Rapid IPS WQHD panel, Quantum Dot renk doğruluğu ve 170Hz yenileme hızı.',
        price: 10999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '27" WQHD Rapid IPS', Yenileme: '170Hz', TepkiSüresi: '1ms GTG', Renk: 'Quantum Dot %95 DCI-P3' },
        categoryId: 'Monitör',
        isFeatured: false,
      },
      {
        name: 'ASUS ZenScreen Fold OLED',
        brand: 'ASUS',
        description: 'Dünyanın ilk katlanabilir 17.3 inç QHD+ OLED taşınabilir monitörü.',
        price: 64999.00,
        stock: 8,
        imageUrl: '/hero-banners/zenscreen-fold.png',
        specs: { Ekran: '17.3" Katlanabilir OLED', Çözünürlük: '2560 x 1920 QHD+', Portlar: 'Dual USB Type-C, Mini HDMI', Ağırlık: '1.17 kg' },
        categoryId: 'Monitör',
        isFeatured: true,
      },
      {
        name: 'ASUS ROG Swift OLED PG32UCDM 32"',
        brand: 'ASUS',
        description: '32 inç 4K 240Hz QD-OLED oyuncu monitörü, 3. Nesil QD-OLED panel ve özel soğutucu.',
        price: 54999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '31.5" 4K QD-OLED Gen 3', Yenileme: '240Hz', TepkiSüresi: '0.03ms', Kasa: 'Custom Heatsink Graphene' },
        categoryId: 'Monitör',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  9. MOUSE (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Razer Basilisk V3 Pro 35K',
        brand: 'Razer',
        description: 'Focus Pro 35K Gen-2 Optik Sensör, HyperScroll Eğimli Çark ve 13 programlanabilir tuş.',
        price: 5999.00,
        stock: 40,
        imageUrl: '/hero-banners/basilisk-v3-pro.png',
        specs: { Sensör: 'Focus Pro 35K Gen-2', Tuşlar: '13 Programlanabilir', Çark: 'HyperScroll Smart-Wheel', Bağlantı: 'Razer HyperSpeed Wireless' },
        categoryId: 'Mouse',
        isFeatured: true,
      },
      {
        name: 'Razer DeathAdder V3 Pro',
        brand: 'Razer',
        description: '63g ultra hafif ergonomik tasarım, Focus Pro 30K sensör ve Gen-3 optik mouse switchleri.',
        price: 4999.00,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
        specs: { Ağırlık: '63 gram', Sensör: 'Focus Pro 30K (30,000 DPI)', Switch: 'Optical Mouse Switches Gen-3', Pil: '90 Saat' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'Razer Viper V3 Pro',
        brand: 'Razer',
        description: '54g e-spor onaylı simetrik tasarım, Focus Pro 35K Gen-2 sensör ve 8000Hz polling oranı.',
        price: 6499.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
        specs: { Ağırlık: '54 gram', PollingRate: '8000Hz HyperPolling', Sensör: 'Focus Pro 35K', Pil: '95 Saat' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'Logitech G PRO X SUPERLIGHT 2',
        brand: 'Logitech',
        description: '60 gram altı ultra hafif tasarım, HERO 2 sensör (32,000 DPI) ve LIGHTFORCE hibrid anahtarlar.',
        price: 5499.00,
        stock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1626218174358-7769486c4b79?w=600&auto=format&fit=crop&q=80',
        specs: { Ağırlık: '60 gram', Sensör: 'HERO 2 (32,000 DPI)', PollingRate: '4000Hz (Software update)', Pil: '95 Saat' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'Logitech MX Master 3S',
        brand: 'Logitech',
        description: '8000 DPI camda dahi çalışan sensör, MagSpeed sessiz elektromanyetik kaydırma çarkı.',
        price: 4299.00,
        stock: 45,
        imageUrl: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: 'Darkfield 8000 DPI', Çark: 'MagSpeed Elektromanyetik', Tıklama: 'Quiet Clicks (%90 sessiz)', ÇokluCihaz: '3 Cihaz Flow' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'GravaStar Mercury M1 Pro',
        brand: 'GravaStar',
        description: 'Magnezyum alaşım içi boş bilim kurgu iskelet gövde, PAW3395 sensör 26.000 DPI.',
        price: 4999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?w=600&auto=format&fit=crop&q=80',
        specs: { Malzeme: 'Magnezyum Alaşım', Sensör: 'PAW3395 (26,000 DPI)', PollingRate: '4K Hz alıcı destekli', RGB: 'Glow RGB' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'GravaStar Mercury M2 Wireless Gaming Mouse',
        brand: 'GravaStar',
        description: 'Hafif içi boş petek bilim kurgu iskelet tasarım, 1K Hz alıcı, PAW3395 26K DPI sensör.',
        price: 3899.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=80',
        specs: { Ağırlık: '79g', Sensör: 'PAW3395 (26,000 DPI)', Bağlantı: '2.4G + BT + Kablolu', Pil: '80 Saat' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'SteelSeries Aerox 5 Wireless',
        brand: 'SteelSeries',
        description: '74g hafif petek tasarımı, TrueMove Air sensör, IP54 AquaBarrier su koruması ve 9 tuş.',
        price: 3999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1613141411244-0e4ac259d217?w=600&auto=format&fit=crop&q=80',
        specs: { Ağırlık: '74g', Sensör: 'TrueMove Air (18,000 CPI)', SuKoruma: 'IP54 AquaBarrier', Pil: '180 Saat' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'SteelSeries Rival 5',
        brand: 'SteelSeries',
        description: '9 tuşlu hassas ergomik tasarım, TrueMove Air sensör ve 10 bölgeli PrismSync RGB.',
        price: 2499.00,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=600&auto=format&fit=crop&q=80',
        specs: { Tuşlar: '9 Programlanabilir E-spor Tuşu', Sensör: 'TrueMove Air', Ağırlık: '85g', RGB: '10 Bölge PrismSync' },
        categoryId: 'Mouse',
        isFeatured: false,
      },
      {
        name: 'MSI Clutch GM51 Lightweight',
        brand: 'MSI',
        description: 'PAW-3395 optik sensör (26,000 DPI), MSI Diamond LightGrip ve 8K Hz polling hızı desteği.',
        price: 3499.00,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
        specs: { Sensör: 'PAW-3395 (26,000 DPI)', YanYüzey: 'MSI Diamond LightGrip', Kablo: 'MSI FriXionFree', Ağırlık: '75g' },
        categoryId: 'Mouse',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  10. OYUN (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Sony PlayStation 5 Pro',
        brand: 'Sony',
        description: '2TB SSD depolama, PSSR Yapay Zeka Geliştirilmiş Çözünürlük, Gelişmiş Işın İzleme konsolu.',
        price: 34999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80',
        specs: { Depolama: '2 TB NVMe SSD', GPU: '%67 daha fazla CU', Özellik: 'PlayStation Spectral Super Resolution (PSSR)', 'Wi-Fi': 'Wi-Fi 7' },
        categoryId: 'Oyun',
        isFeatured: true,
      },
      {
        name: 'PlayStation VR2 Kiti',
        brand: 'Sony',
        description: '4K HDR OLED ekranlar, 110° görüş alanı, Göz Takibi ve Sense kontrolcüler ile sanal gerçeklik.',
        price: 21999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '4K HDR OLED (2000x2040 per eye)', Yenileme: '90Hz / 120Hz', Takip: 'Göz Takibi (Eye Tracking)', Ses: '3D Audio' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'Microsoft Xbox Series X',
        brand: 'Microsoft',
        description: '12 Teraflop grafik gücü, 1TB SSD, Quick Resume ve 4K 120fps gerçek oyun deneyimi.',
        price: 26999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: '12 TFLOPS AMD RDNA 2', Depolama: '1 TB Custom NVMe', Çözünürlük: 'True 4K @ 120fps' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'Xbox Series S 1TB Carbon Black',
        brand: 'Microsoft',
        description: 'Şık mat siyah tasarım, 1TB SSD depolama, 120fps hız ve Xbox Game Pass ekosistemi.',
        price: 17499.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&auto=format&fit=crop&q=80',
        specs: { Depolama: '1 TB NVMe SSD', Renk: 'Carbon Black', Performans: '1440p @ 120fps', Ses: 'Dolby Atmos / DTS:X' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'Nintendo Switch OLED',
        brand: 'Nintendo',
        description: '7 inç canlı OLED ekran, geniş ayarlanabilir stant, kablolu LAN portlu dock.',
        price: 14999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '7" OLED', DahiliDepolama: '64 GB', Modlar: 'TV, Masaüstü, Elde Uçuş' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'My Arcade Atari Retro Konsol',
        brand: 'My Arcade',
        description: '200+ nostaljik klasik Atari oyunu, HDMI 720p çıkış ve kablosuz joystickler.',
        price: 4999.00,
        stock: 40,
        imageUrl: '/hero-banners/gamestation-atari.png',
        specs: { Oyunlar: '200+ Lisanslı Atari Oyunu', Çıkış: 'HDMI 720p HD', Kontrolcüler: '2x Kablosuz 2.4GHz Joystick' },
        categoryId: 'Oyun',
        isFeatured: true,
      },
      {
        name: 'My Arcade PAC-MAN Micro Player',
        brand: 'My Arcade',
        description: '6.75 inç lisanslı minyatür arcade atari dolabı, tam renkli 2.75 inç ekran.',
        price: 1999.00,
        stock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?w=600&auto=format&fit=crop&q=80',
        specs: { Oyun: 'Orijinal Lisanslı PAC-MAN Arcade', Ekran: '2.75" Renkli', Ses: 'Dahili Hoparlör + 3.5mm Jak' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'Razer Edge Gaming Handheld',
        brand: 'Razer',
        description: 'Snapdragon G3x Gen 1 çipli, 144Hz AMOLED ekranlı Android el oyun konsolu.',
        price: 18999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'Snapdragon G3x Gen 1', Ekran: '6.8" FHD+ AMOLED 144Hz', Kontrolcü: 'Razer Kishi V2 Pro' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'Lenovo Legion Go',
        brand: 'Lenovo',
        description: 'AMD Ryzen Z1 Extreme, 8.8 inç QHD+ 144Hz dokunmatik ekran, çıkarılabilir TrueStrike kontrolcüler.',
        price: 32999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&auto=format&fit=crop&q=80',
        specs: { İşlemci: 'AMD Ryzen Z1 Extreme', Ekran: '8.8" QHD+ 144Hz', RAM: '16 GB LPDDR5X', Depolama: '512 GB PCIe 4.0' },
        categoryId: 'Oyun',
        isFeatured: false,
      },
      {
        name: 'Valve Steam Deck OLED',
        brand: 'Valve',
        description: '7.4 inç 90Hz HDR OLED ekran, 6nm APU, daha uzun pil ömrü ve Wi-Fi 6E desteği.',
        price: 27999.00,
        stock: 22,
        imageUrl: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '7.4" HDR OLED 90Hz', APU: '6nm AMD Sephiroth', Depolama: '512 GB NVMe SSD', Batarya: '50Wh (3-12 saat)' },
        categoryId: 'Oyun',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  11. SES (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Samsung HW-Q990D Soundbar',
        brand: 'Samsung',
        description: '11.1.4 kanal gerçek kablosuz Dolby Atmos ses sistemi, Q-Symphony ve HDMI 2.1 passthrough.',
        price: 36999.00,
        stock: 14,
        imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
        specs: { Kanal: '11.1.4 Kanal', SesTeknolojisi: 'Wireless Dolby Atmos', Hoparlörler: 'Soundbar + Subwoofer + Çift Arka' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'Xiaomi Sound Pocket Bluetooth Hoparlör',
        brand: 'Xiaomi',
        description: '5W gücünde IP67 su ve toz geçirmez cep tipi kablosuz hoparlör.',
        price: 899.00,
        stock: 60,
        imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '5W RMS', Pil: '10 Saat', SuKoruma: 'IP67', Bağlantı: 'Bluetooth 5.4' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'JBL Boombox 3 Wi-Fi',
        brand: 'JBL',
        description: 'Dolby Atmos destekli Wi-Fi/Bluetooth taşınabilir hoparlör, 24 saat pil ömrü ve derin bas.',
        price: 21999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '180W RMS', Bağlantı: 'Wi-Fi 6 + Bluetooth 5.3', Ses: '3-Yönlü Hoparlör + Dolby Atmos', Pil: '24 Saat' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'JBL PartyBox Stage 320',
        brand: 'JBL',
        description: '240W RMS güç, dahili ışık gösterisi, teleskopik sap ve tekerlekli parti hoparlörü.',
        price: 24999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '240W RMS', IşıkŞovu: 'Futuristic Lightshow', Pil: '18 Saat (Değiştirilebilir)', MikrofonGirişi: 'Çift Mikrofon & Gitar' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'LG Soundbar S95QR',
        brand: 'LG',
        description: '9.1.5 kanal 810W devasa güç, dünyanın ilk üçlü üst atımlı kanala sahip Dolby Atmos soundbar.',
        price: 34999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '810W RMS', Kanal: '9.1.5 Kanal', Ses: 'IMAX Enhanced + Dolby Atmos', Meridian: 'Meridian Ses Ayarı' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'LG XBOOM CK43',
        brand: 'LG',
        description: '300W RMS güç, dual USB bağlantısı, DJ efektleri ve EZ File Search özellikli mini müzik seti.',
        price: 8999.00,
        stock: 22,
        imageUrl: '/hero-banners/ck43-x-boom.png',
        specs: { Güç: '300W RMS', Bağlantı: 'Bluetooth, Çift USB, AUX, CD', Özellik: 'Wireless Party Link', DJModları: 'EZ File Search & DJ Sharing' },
        categoryId: 'Ses',
        isFeatured: true,
      },
      {
        name: 'Marshall Stanmore III',
        brand: 'Marshall',
        description: 'Ikonik retro tasarım, genişletilmiş ses sahnesi ve Bluetooth 5.2 kablosuz ev hoparlörü.',
        price: 15999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '80W D-Sınıfı Amfi', Bağlantı: 'Bluetooth 5.2 / RCA / 3.5mm', Boyut: '350 x 203 x 188 mm' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'Marshall Emberton II',
        brand: 'Marshall',
        description: '360° True Stereophonic ses, IP67 su geçirmez ikonik el tipi taşınabilir hoparlör.',
        price: 7499.00,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '20W RMS', Ses: '360° True Stereophonic', Pil: '30+ Saat', Koruma: 'IP67 Su & Toz' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'Bose SoundLink Max',
        brand: 'Bose',
        description: 'Bose stereo bas performansı, IP67 su geçirmez silikon kaplama ve 20 saatlik batarya ömrü.',
        price: 17999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&auto=format&fit=crop&q=80',
        specs: { Pil: '20 Saat', Koruma: 'IP67 Su & Toz', Şarj: 'USB-C In/Out (Powerbank)', Kulp: 'Çıkarılabilir Halat Kulp' },
        categoryId: 'Ses',
        isFeatured: false,
      },
      {
        name: 'Harman Kardon Onyx Studio 8',
        brand: 'Harman Kardon',
        description: 'Geri dönüştürülmüş malzemelerden üretilen ikonik yuvarlak tasarım ve otomatik kalibrasyonlu Hi-Fi ses.',
        price: 9999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=600&auto=format&fit=crop&q=80',
        specs: { Güç: '50W RMS', Kalibrasyon: 'Otomatik Oda Akustiği', Pil: '8 Saat', Kulp: 'Anodize Alüminyum Tutacak' },
        categoryId: 'Ses',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  12. TELEFON (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'iPhone 16 Pro Max',
        brand: 'Apple',
        description: 'A18 Pro çip, 48MP Fusion kamera, Titanyum gövde ve 6.9 inç Super Retina XDR OLED ekran.',
        price: 84999.00,
        originalPrice: 89999.00,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.9" OLED 120Hz', İşlemci: 'A18 Pro', RAM: '8 GB', Depolama: '256 GB', Kamera: '48 MP + 48 MP + 12 MP' },
        categoryId: 'Telefon',
        isFeatured: true,
      },
      {
        name: 'iPhone 15 Pro',
        brand: 'Apple',
        description: 'A17 Pro çip, Titanyum tasarım, Eylem Butonu ve 3x Optik zoom kamerasında üstün performans.',
        price: 64999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.1" Super Retina XDR', İşlemci: 'A17 Pro', RAM: '8 GB', Depolama: '128 GB' },
        categoryId: 'Telefon',
        isFeatured: false,
      },
      {
        name: 'Samsung Galaxy S25 Ultra',
        brand: 'Samsung',
        description: 'Snapdragon 8 Elite, Galaxy AI, 200MP kamera, entegre S Pen ve 6.9 inç Dynamic AMOLED 2X.',
        price: 74999.00,
        originalPrice: 79999.00,
        stock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.9" AMOLED 2X', İşlemci: 'Snapdragon 8 Elite', RAM: '12 GB', Depolama: '256 GB', Kamera: '200 MP + 50 MP + 50 MP' },
        categoryId: 'Telefon',
        isFeatured: true,
      },
      {
        name: 'Samsung Galaxy Z Fold 6',
        brand: 'Samsung',
        description: '7.6 inç katlanabilir iç ekran, Snapdragon 8 Gen 3, ultra ince zırh alüminyum menteşe.',
        price: 71999.00,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&auto=format&fit=crop&q=80',
        specs: { İçEkran: '7.6" Dynamic AMOLED 2X', İşlemci: 'Snapdragon 8 Gen 3', RAM: '12 GB', Depolama: '512 GB' },
        categoryId: 'Telefon',
        isFeatured: false,
      },
      {
        name: 'Xiaomi 15 Ultra',
        brand: 'Xiaomi',
        description: 'Leica 1 inç ana sensörlü kamera sistemi, Snapdragon 8 Elite ve 6.73 inç 2K WQHD+ ekran.',
        price: 52999.00,
        stock: 18,
        imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.73" WQHD+ AMOLED', İşlemci: 'Snapdragon 8 Elite', RAM: '16 GB', Depolama: '512 GB' },
        categoryId: 'Telefon',
        isFeatured: false,
      },
      {
        name: 'Xiaomi 14T Pro',
        brand: 'Xiaomi',
        description: 'MediaTek Dimensity 9300+, Leica Summilux optik lens, 120W HyperCharge şarj.',
        price: 36999.00,
        stock: 28,
        imageUrl: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79e2?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.67" AMOLED 144Hz', İşlemci: 'Dimensity 9300+', Şarj: '120W Kablolu / 50W Kablosuz', Kamera: '50 MP Leica' },
        categoryId: 'Telefon',
        isFeatured: false,
      },
      {
        name: 'OPPO Find X8 Pro',
        brand: 'OPPO',
        description: 'Hasselblad kamera sistemi, MediaTek Dimensity 9400 ve 5910 mAh dev bataryasıyla ön planda.',
        price: 47999.00,
        stock: 22,
        imageUrl: '/hero-banners/find-x9-pro.png',
        specs: { Ekran: '6.78" LTPO AMOLED', İşlemci: 'Dimensity 9400', RAM: '16 GB', Depolama: '512 GB', Kamera: '50 MP Quad Hasselblad' },
        categoryId: 'Telefon',
        isFeatured: true,
      },
      {
        name: 'Nothing Phone (2a) Plus',
        brand: 'Nothing',
        description: 'Şeffaf tasarımlı Glyph LED ışık arayüzü, Dimensity 7350 Pro 5G ve 50MP selfie kamerası.',
        price: 21999.00,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.7" AMOLED 120Hz', İşlemci: 'Dimensity 7350 Pro', RAM: '12 GB', Depolama: '256 GB' },
        categoryId: 'Telefon',
        isFeatured: false,
      },
      {
        name: 'Google Pixel 9 Pro',
        brand: 'Google',
        description: 'Tensor G4 işlemci, 16GB RAM, Google AI ve 7 yıl işletim sistemi güncelleme garantisi.',
        price: 44999.00,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1533228876829-65c94e7b5025?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.3" Super Actua LTPO OLED', İşlemci: 'Google Tensor G4', RAM: '16 GB', Depolama: '128 GB' },
        categoryId: 'Telefon',
        isFeatured: false,
      },
      {
        name: 'Huawei Mate 60 Pro',
        brand: 'Huawei',
        description: 'Kirin 9000s işlemci, XMAGE üçlü kamera sistemi, Kunlun Glass 2 korumalı ekran.',
        price: 49999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '6.82" LTPO OLED', İşlemci: 'Kirin 9000s', RAM: '12 GB', Depolama: '512 GB' },
        categoryId: 'Telefon',
        isFeatured: false,
      },

      // ═══════════════════════════════════════════
      //  13. TELEVİZYON (10 Ürün)
      // ═══════════════════════════════════════════
      {
        name: 'Samsung Neo QLED 8K QN900D 75"',
        brand: 'Samsung',
        description: 'NQ8 AI Gen3 İşlemci, 8K çözünürlük, Infinity Air tasarım ve 90W 6.2.4CH ses.',
        price: 179999.00,
        stock: 4,
        imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '75" 8K Neo QLED', İşlemci: 'NQ8 AI Gen3', Yenileme: '240Hz (4K) / 120Hz (8K)', Ses: '90W 6.2.4CH' },
        categoryId: 'Televizyon',
        isFeatured: true,
      },
      {
        name: 'Samsung OLED S95D 65"',
        brand: 'Samsung',
        description: 'Parlama yapmayan OLED ekran paneli, NQ4 AI Gen2 işlemci ve Quantum HDR OLED Pro.',
        price: 89999.00,
        stock: 10,
        imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '65" 4K OLED Glare-Free', İşlemci: 'NQ4 AI Gen2', Yenileme: '144Hz', Ses: '70W 4.2.2CH' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'Samsung The Frame 55" LS03D',
        brand: 'Samsung',
        description: 'Sanat eseri çerçeve tasarımı, QLED 4K, Art Store, özelleştirilebilir çerçeve.',
        price: 32999.00,
        stock: 14,
        imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '55" 4K QLED', İşlemci: 'Quantum 4K', 'Yenileme Hızı': '120Hz', HDR: 'Quantum HDR' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'LG OLED evo C4 65"',
        brand: 'LG',
        description: 'α9 AI Processor 4K Gen7, Brightness Booster, 144Hz VRR ve Dolby Vision/Atmos.',
        price: 74999.00,
        stock: 14,
        imageUrl: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '65" 4K OLED evo', İşlemci: 'α9 AI Gen7', VRR: '144Hz AMD FreeSync Premium', AkıllıSistem: 'webOS 24' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'LG QNED MiniLED 86" TV',
        brand: 'LG',
        description: '86 inç devasa Mini LED ekran, α7 AI Gen7 işlemci, 120Hz ve Dolby Atmos ses kalitesi.',
        price: 79999.00,
        stock: 5,
        imageUrl: '/hero-banners/lg-65qned87b6a.png',
        specs: { Ekran: '86" 4K QNED Mini LED', İşlemci: 'α7 AI Gen7', Yenileme: '120Hz', Ses: 'Dolby Atmos 20W', AkıllıTV: 'webOS 24' },
        categoryId: 'Televizyon',
        isFeatured: true,
      },
      {
        name: 'Sony BRAVIA XR A95L OLED 65"',
        brand: 'Sony',
        description: 'QD-OLED panel, Cognitive Processor XR, Acoustic Surface Audio+ ekran ses teknolojisi.',
        price: 119999.00,
        stock: 6,
        imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '65" 4K QD-OLED', İşlemci: 'Cognitive Processor XR', Ses: 'Acoustic Surface Audio+', OS: 'Google TV' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'Sony BRAVIA 9 QLED 75"',
        brand: 'Sony',
        description: 'High Peak Brightness Mini LED ekran, XR Backlight Master Drive, XR Processor.',
        price: 139999.00,
        stock: 5,
        imageUrl: 'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '75" 4K Mini LED', İşlemci: 'XR Processor', Sürücü: 'XR Backlight Master Drive', Ses: 'Acoustic Multi-Audio+' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'Xiaomi TV Max 86"',
        brand: 'Xiaomi',
        description: '86 inç devasa 4K ekran, 120Hz MEMC hareket yumuşatma, Dolby Vision IQ ve Google TV.',
        price: 49999.00,
        stock: 12,
        imageUrl: 'https://images.unsplash.com/photo-1528928441742-b4ccac1bb04c?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '86" 4K UHD LED', Yenileme: '120Hz MEMC', Ses: '30W Dolby Atmos', OS: 'Google TV' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'Philips Ambilight OLED 808 65"',
        brand: 'Philips',
        description: '3 taraflı Ambilight arka aydınlatma, P5 AI Perfect Picture Engine ve Bowers & Wilkins ses.',
        price: 69999.00,
        stock: 9,
        imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '65" 4K OLED', Aydınlatma: '3 Taraflı Ambilight', İşlemci: 'P5 AI Gen7', Yenileme: '120Hz' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
      {
        name: 'TCL 75C845 Mini LED 4K TV',
        brand: 'TCL',
        description: '2000 nite varan tepe parlaklık, Mini LED lokal karartma bölgeleri, 144Hz VRR ve Onkyo 2.1 ses.',
        price: 54999.00,
        stock: 16,
        imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
        specs: { Ekran: '75" 4K Mini LED', Parlaklık: '2000 nits', Yenileme: '144Hz VRR', Ses: '60W Onkyo 2.1' },
        categoryId: 'Televizyon',
        isFeatured: false,
      },
    ];

    // Category adlarını ID'lere çevir
    const productsWithCategoryIds = allProducts.map((p) => ({
      ...p,
      categoryId: cats[p.categoryId],
    }));

    await Product.bulkCreate(productsWithCategoryIds);
    console.log(`✅ Toplam ${allProducts.length} ürün oluşturuldu (13 kategoride her biri tam 10 ürün).`);

    console.log('🎉 Seed işlemi başarıyla tamamlandı.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed sırasında hata:', err.message);
    console.error(err);
    process.exit(1);
  }
}

seed();